name: actions

on:
  pull_request:
  push:
    paths:
      - 'actions/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: ./actions/envtest
      - uses: ./actions/kubectl
      - uses: ./actions/kustomize
      - uses: ./actions/helm
      - uses: ./actions/kubebuilder
