name: fuzz

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - id: go-env
      run: |
        echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"
    - name: Restore Go cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-env.outputs.go-mod-cache }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - name: Smoke test Fuzzers
      run: make fuzz-smoketest
